Bugfix: git-number could not handle argument with spaces
    git number commit -m "My message"

would fail because "My message" would be passed to git as two separate
arguments. Git would complain about not recognizing "message":

    error: pathspec 'message' did not match any file(s) known to git.

This commit adds quotations around those arguments which contain spaces
and a test.